[package]
name = "ansee"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
ansi-parser = "0.9.1"
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
image = "0.25.5"
imageproc = "0.25.0"
lazy_static = "1.5.0"
unicode-width = "0.2.0"
